### ISSUE TITLE
Error in ApiClient.cs line 127 , on  etf_pre_timestamp is null

### ISSUE THREAD

**Issue by boyyao** [gateio/gateapi-csharp#1]
json:
{"currency_pair":"MKR_USDT","last":"2255","lowest_ask":"2263.71","highest_bid":"2244.4","change_percentage":"-11.66","base_volume":"130.233640705","quote_volume":"301239.0357505955","high_24h":"2577.25","low_24h":"2019.52","etf_net_value":null,"etf_pre_net_value":null,"etf_pre_timestamp":null,"etf_leverage":null}

error msg
Io.Gate.GateApi.Client.ApiException:“Error converting value {null} to type 'System.Int64'. Path '[0].etf_pre_timestamp', line 1, position 294.”

**Comment by revilwang** [comment]
Problem acknowledged. I'll report this issue back the API implementation.

**Comment by revilwang** [comment]
The latest 4.19.1 version mark Etf* values as nullable. Upgrade to the latest version to fix this problem
