### ISSUE TITLE
Withdraw assets to new wallet address

### ISSUE THREAD

**Issue by kokazani** [gateio/gateapi-csharp#13]
Hello everyone,

I am trying to send assets (eg. USDT) from gate.io to binance.

From the side of gate.io, I have never sent USDT to binance before. So the withdrawal address is new and of course not whitelisted in gate.io.

The function for withdraw is:

```
Public Async Function WithdrawAsync(ByVal coin As String, ByVal qnty As Decimal, ByVal destinationWalletAddress As String, ByVal network As String) As Task(Of LedgerRecord)

Dim culture As CultureInfo
culture = CultureInfo.CreateSpecificCulture("en-US")

Dim w As New LedgerRecord(qnty.ToString("G", CultureInfo.InvariantCulture), coin, destinationWalletAddress, "", network)
Console.WriteLine(w.ToJson())

Return Await withdrawalApi.WithdrawAsync(w)

End Function
```
The ledger record is (binance USDT wallet address under TRON network):
`{
  "amount": "50.2",
  "currency": "USDT",
  "address": "TE7fxqLHp1UvnGtc5w3wTHWPEqpuHsp5zQ",
  "memo": "",
  "chain": "TRX"
}`

Every time, the response has this exception (Io.Gate.GateApi.Client.GateApiException):
Message: `{"message":"Error: only used addresses or verified addresses are allowed for api withdrawal","label":"INVALID_PARAM_VALUE"}`

Using NuGet version 4.22.2
So, is there any way to by pass this error and withdraw assets to new (never used before) wallet address?
Unfortunately, after chatting with gate.io support, the functionality of address whitelisting is not implemented yet.
Is there any issue with my code, or I missing something?

Thank you in advance,
Kostas

**Comment by revilwang** [comment]
As the error message said, only address used on web console can be used in API. You can make a small amount transfer on the web, then use API to do the subsequent.
