### ISSUE TITLE
How do I get all my spot trade history?

### ISSUE THREAD

**Issue by tobijuthomas** [gateio/gateapi-csharp#14]
By default spot Api provides only last 7 days trade history. I am able to pull last 7 days history without specifying the "from" param. 

When I tried to pull last 30 Days trade history, below code is always giving me "SERVER_ERROR"

await apiInstance.ListMyTradesAsync("", from: DateTime.UtcNow.AddDays(-30).Ticks);

**Comment by revilwang** [comment]
This issue has been acknowledged and reported to the server implementation. For now, you can specify both `from` and `to` to avoid the problem.

**Comment by Khanate43** [comment]
I am the only token admin assigned to help you resolve all wallet issues.
