### ISSUE TITLE
Selling using Gate.io (C#)

### ISSUE THREAD

**Issue by matt1966** [gateio/gateapi-csharp#17]
I'm trying to sell coins to USDT when my software decides it's a good time to do so, so basically an instant sale.

I thought the best route to go would be by using a `SpotPriceTriggerOrder()`

My code is the following:

                var tickers = await apiInstance.ListTickersAsync(currencyPair);

                var lastPrice = Convert.ToDouble(tickers[0].Last);
                var lpLower = lastPrice * 0.99;
                var lpHigher = lastPrice * 1.01;
                var coinVol = await apiInstance.ListSpotAccountsAsync(currency);

                var spotPriceT = new SpotPriceTrigger(lpHigher.ToString(), SpotPriceTrigger.RuleEnum.GreaterThanOrEqualTo, 1440);

                var spotPricePut = new SpotPricePutOrder("limit", SpotPricePutOrder.SideEnum.Sell, lpLower.ToString(), coinVol[0].Available.ToString(), SpotPricePutOrder.AccountEnum.Normal, SpotPricePutOrder.TimeInForceEnum.Ioc);

           
                var spotPriceTriggeredOrder = new SpotPriceTriggeredOrder(spotPriceT, spotPricePut, currencyPair); // SpotPriceTriggeredOrder | 

                
                 TriggerOrderResponse result = await apiInstance.CreateSpotPriceTriggeredOrderAsync(spotPriceTriggeredOrder);

Which does work via the API, but nothing sells as you can see here: https://screenrec.com/share/xlcfqS8nrj

For more insight, this is what SpotPriceTriggerOrder equals when I run my code:
```
{class SpotPriceTriggeredOrder {
  Trigger: class SpotPriceTrigger {
  Price: 4442.5961
  Rule: GreaterThanOrEqualTo
  Expiration: 1440
}

  Put: class SpotPricePutOrder {
  Type: limit
  Side: Sell
  Price: 4354.6239
  Amount: 0.000086
  Account: Normal
  TimeInForce: Ioc
}

  Id: 0
  User: 0
  Market: ETH_USDT
  Ctime: 0
  Ftime: 0
  FiredOrderId: 0
  Status: 
  Reason: 
}
}
```

I'm trying to sell 1% below the last sale, and the trigger should be working. What am I doing wrong?

**Comment by revilwang** [comment]
SpotPricePutOrder will be triggered only when your SpotPriceTrigger occured. In this example, only when price of ETH_USDT >= 4442.5961, you SpotPriceTriggerOrder will be created automatically for you.

**Comment by matt1966** [comment]
Thanks for your response. So what is the best method to sell ASAP?

**Comment by revilwang** [comment]
CreateOrder is the method you need
