### ISSUE TITLE
How to add proxy support

### ISSUE THREAD

**Issue by boyyao** [gateio/gateapi-csharp#2]
I want to use this API through proxy. How can I code it? thx~

**Comment by revilwang** [comment]
Not supported at the moment, but RestSharp is used as the http client. You can download the source code, and set the proxy in `Exec` function in `ApiClient.cs` file and add line 

```c#
client.Proxy = new WebProxy("http://<your proxy host>:<your proxy port>");
```

before the `client.Execute<T>(req)` line.

We'll try to add this into configuration, so you don't need to modify the source code yourself.

**Comment by boyyao** [comment]
Thank you. I hope it can be used in the next version. And hope to support http and socks proxy

**Comment by revilwang** [comment]
New version 4.20.0 is published. You can now set a `IWebProxy` to `Configuration`, so that the client will use it.

```c#
Configuration config = new Configuration();
config.BasePath = "https://api.gateio.ws/api/v4";
config.Proxy = new WebProxy("<your http proxy host>", <your http proxy port>);
```

Because RestSharp does not support socks proxy, so it is not possible for us right now to support it.

**Comment by boyyao** [comment]
thx...
I noticed that the API reconnects SSL every time. Hope to keepactive

**Comment by revilwang** [comment]
I used the demo application, and captured traffic using wireshark, the result shows only one time SSL negotiation.
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/8424970/112566623-4ef67280-8e1a-11eb-8037-de89a4ee2aab.png">
