### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by zenchanhk** [gateio/gateapi-csharp#21]
今天下午开始，很多functions都会传回下面这个exception：

Io.Gate.GateApi.Client.ApiException: 'Error calling GetPosition: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Io.Gate.GateApi.Model.Position' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.'

之前跑得好好，请问是啥问题啊？

**Comment by zenchanhk** [comment]
FuturesApi 会有这个问题，WalletApi没有。其他的api没用过，不知道。

**Comment by revilwang** [comment]
是因为开了双向仓位吗？如果是开了双向仓位，需要使用双仓相关的查询接口

**Comment by zenchanhk** [comment]
哦哦，我看看，谢谢

**Comment by zenchanhk** [comment]
是的，我切换成Dual mode了，谢谢

**Comment by zenchanhk** [comment]
@revilwang 请问双仓模式下，如果设定逐仓，还是全仓啊？在单仓模式，UpdatePositionLeverage有个CrossLevergeLimit可以设定（双仓没有），我是在那里设定的，不知道是否有错？

**Comment by revilwang** [comment]
该问题 #22 已经回复，关闭重复问题
