### ISSUE TITLE
请问双仓模式下，如果设定逐仓，还是全仓？

### ISSUE THREAD

**Issue by zenchanhk** [gateio/gateapi-csharp#22]
请问双仓模式下，如果设定逐仓，还是全仓啊？在单仓模式，UpdatePositionLeverage有个CrossLevergeLimit可以设定（双仓没有），我是在那里设定的，不知道是否有错？

**Comment by revilwang** [comment]
版本已经更新，双仓模式也已经增加了 CrossLeverageLimit 参数
