### ISSUE TITLE
Error calling List OrderBook: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by forReason** [gateio/gateapi-csharp#26]
From time to time I receive this error Message:
```
The SSL connection could not be established, see inner exception.
Error calling List OrderBook: The SSL connection could not be established, see inner exception.
``` 
Line causing the error:
```
OrderBook requestResult = API._spotApi.ListOrderBook(currencyPair.UnderscoredString, orderDepthAggreation, depthLimit, returnOrderbookId);
```

whats causing the error or how to mitigate it?

**Comment by revilwang** [comment]
Seems the connection to the server is not stable. Do you encounter such errors while calling other methods? Where is your client located?

**Comment by forReason** [comment]
Haven't gotten this error on another method yet. Latency/response time seems quite high with > 1s on average.
okx response times are around ~20ms for an orderbook.

Client is located in switzerland on 10gb network connection

**Comment by forReason** [comment]
issue seems to be resolved now,

**Comment by forReason** [comment]
Coming bach to this. As of today, I am unable to open a connection from any of my computers at home.

From my laptop at work, It worked.
Different windows 10 cersions are involved. I did a wireshark. The server bumps me, does not accept the client hello:
![image](https://github.com/gateio/gateapi-csharp/assets/12736950/9ba27065-3816-4601-ab1b-419c9afbb829)
[gateshark.zip](https://github.com/gateio/gateapi-csharp/files/11758743/gateshark.zip)


I wonder if thats some kind of ban behaviour? Although Gate works totally fine in the webbrowser
