### ISSUE TITLE
walletApi.GetTradeFee does not include GT Fees

### ISSUE THREAD

**Issue by forReason** [gateio/gateapi-csharp#28]
I have an issue with `WalletApi.GetFees(CurrencyPair)`:

The request executes fine. Fees are returned but GT Trading fee is 0.
My request:
```
TradeFee result = API._walletApi.GetTradeFee(null);
```

result:
![image](https://user-images.githubusercontent.com/12736950/168417743-2f57b183-77d7-4cdd-9d2a-b2afd1e6232d.png)

GT discount also seems to be false.
I have tried enabling gt trading on the gate.io account / fees section but it did not replicate in the API. Is there a time/synchronisation off set or do I have to set "gt trading fees" manually somewhere in the API?

**Comment by revilwang** [comment]
When you update GT discount settings, it will take effect in about 5 minutes. You can try to retrieve the status once again and check if the status has been changed in the API response.
