### ISSUE TITLE
How I can use Nuget package to get account balance?

### ISSUE THREAD

**Issue by zydjohnHotmail** [gateio/gateapi-csharp#29]
Hello:
I just create V4 API keys for my Gate.IO account, and I want to use Nuget package: Io.Gate.GateApi version 4.26.0 to get my account balance.
But I can’t find any code example. I am using C# on Windows 10.
Please show me some code example on how to use V4 API keys to sign HTTP request and get my account balance.
Thanks,

**Comment by revilwang** [comment]
I think [this](https://github.com/gateio/gateapi-csharp/blob/master/docs/SpotApi.md#listspotaccounts) might help

**Comment by zydjohnHotmail** [comment]
Thanks!
