### ISSUE TITLE
Missing market order type

### ISSUE THREAD

**Issue by masherak** [gateio/gateapi-csharp#32]
Hello, there is no possibility to create the new Order with "Market" order type? In "Order.TypeEnum" I can see just Limit, why? I think API support this functionality or not ? Thank you

**Comment by masherak** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/15813908/204932771-1d76e61a-2c5f-472a-a62a-a77426a2fac0.png">

**Comment by revilwang** [comment]
We'll update the SDK ASAP in this week

**Comment by timaiv** [comment]
> We'll update the SDK ASAP in this week

Hi!
Currently (01-09.12.2022) gate.io api returns "**internal server error**" message for **market** orders in batch endpoint, but actually they were successful filled, reproducible 100%.

**Comment by revilwang** [comment]
Hi, can you please give a request detail on this problem? Thanks

**Comment by timaiv** [comment]
> Hi, can you please give a request detail on this problem? Thanks

Hi!
I can't reproduce internal server error today (i think u fixed) but I get a different error "**Error converting value "market" to type 'System.Nullable`1[Io.Gate.GateApi.Model.BatchOrder+TypeEnum]'. Path '[0].type', line 1, position 282.**"


In `Order` class we have
```cs
public enum TypeEnum
        {
            //
            // Summary:
            //     Enum Limit for value: limit
            Limit = 1,
            //
            // Summary:
            //     Enum Market for value: market
            Market = 2
        }
```
but in `BatchOrder`

```cs
public enum TypeEnum
        {
            //
            // Summary:
            //     Enum Limit for value: limit
            Limit = 1
        }
```

**Comment by revilwang** [comment]
Yes, the problem has been acknowledged and resolved.

**Comment by revilwang** [comment]
About the BatchOrder model issue, we'll update a new version later this week

**Comment by timaiv** [comment]
> About the BatchOrder model issue, we'll update a new version later this week

Also we have some other problems (i think bugs) with **MARKET** type order rest api, but it concerns rest api, not this library. Who can we talk to?

**Comment by revilwang** [comment]
You can ask questions directly here

**Comment by timaiv** [comment]
> You can ask questions directly here

Inability to create a request to buy the pair "X_USDT" (the price of which is 0.001$) for $**1.5** using MARKET order.
The order is filled at "1" (and it's interesting that there are no validation errors), I found using api that this pair has precision "0".
For other pair with precision 2, i cant create a request for 1.123$ etc.

From docs. 
Amount - When type is market, it refers to different currency according to side, buy means **quote currency**, BTC_USDT means USDT)

I think this is just a bug, and u thought that pair precision - is precision for **base currency**, but for **MARKET** **BUY** order amount here is **quote currency**.

**Comment by revilwang** [comment]
Seems a bug to me. I'll report the issue.

**Comment by timaiv** [comment]
> Seems a bug to me. I'll report the issue.

Hi! 
Any updates?

**Comment by revilwang** [comment]
The bug has been fixed. SDK is still on the way

**Comment by timaiv** [comment]
> The bug has been fixed. SDK is still on the way

Hi!

As I said, there are still a lot of problems here (even after a month).
One of the problems that has not been fixed. I didn't write about it.

For **MARKET** order (both FOK, IOC) "Status" is always "**Cancelled**" (although order is filled).
Possible, i think that due fact that real FillPrice (or FilledTotal) != quantity.

Ex 1: quantity = "1"
FilledTotal  = "0.9999999999999991911"
FillPrice    = "0.9999999999999991911"	
Left 		 = "0.0000000000000008089"

Ex 2: quantity = "1.123456789"
FilledTotal  = "1.123456788999999349"
FillPrice    = "1.123456788999999349"	

For FOK Status "Cancelled" returned in create response.
For FOK Status "OPEN" returned in create response (with completed FilledTotal, FillPrice), and "Cancelled" for GetOrder request after that.

**Comment by timaiv** [comment]
@revilwang 
One more problem with MARKET order.
Only for MARKET + BUY order is impossible to get **ExecutedInBaseCurrency** using CreateOrders response or even GetOrder response.

- Price is 0.
- All FilledTotal, FillPrice, Amount are quote currency. 

The only one way is call ListMyTradesAsync, and sum all Amount (an here Amount is BaseCurrnecy).
But this leads to a larger list of other problems.
