### ISSUE TITLE
现货api接口查询结果问题

### ISSUE THREAD

**Issue by 406750474** [gateio/gateapi-csharp#5]
现货api接口查询结果 告知"status":"cancelled"，实际订单是成交的

**Comment by revilwang** [comment]
是完全成交的吗

**Comment by 406750474** [comment]
是的

**Comment by revilwang** [comment]
请提供下订单 id

**Comment by 406750474** [comment]
50428320467

**Comment by revilwang** [comment]
后台查询这个单子并未**完全**成交，只有下单时所有的 amount 都被成交时状态才是 closed。如果 left 字段不是 0，不管是因为 IOC 被系统撤销还是用户手动撤销，都是 cancelled

**Comment by 406750474** [comment]
left 字段不是 0，left 部分标识撤销，filled_total不是0， status=cancelled也表示成交
