### ISSUE TITLE
I got "REPEAT_REQUEST" label error when I execute my third SpotPriceTriggerOrder

### ISSUE THREAD

**Issue by ertan2002** [gateio/gateapi-csharp#7]
I have an issue. I would like to create 3 trigger orders for buying and I am creating and executing this order async in a loop.

My aim is that I want to sell my coins in a certain percentage in a certain point. For example:
 I want to sell 40% of my amounts when the price is %4 increased
sell 35% when the price 6% increased
and sell the rest (25%) when the price 8% increased. That means I give different take profits (TP1, TP2, TP3)

and here is my sample code

  var profits= new List<double>()
            {
                singlePrice * 1.04, //4% increased
                singlePrice * 1.06, //6% increased
                singlePrice * 1.08  // 8% increased
        };

  var coinAmounts = new List<double>()
            {
                totalAmount*0.40, // 40% of total amount
                totalAmount*0.35, // 35% of total amount
                totalAmount*0.25, // 25% of total amount
            };
                for (int i = 0; i < profits.Count; i++)
                {
                    var sellPrice = profits[i];
                    var amount = coinAmounts[i];
                    var triggerOrder = createSpotPriceTriggeredOrder(symbol, sellPrice, amount);
                    var triggerOrderResult = await _spotApi.CreateSpotPriceTriggeredOrderAsync(triggerOrder);
                    triggerOrderResonses.Add(triggerOrderResult);
                    Thread.Sleep(500);
                }

createSpotPriceTriggeredOrder method returns a SpotPriceTriggeredOrder instance and I give completly different parameters for the price and the amount ( as you see in my first paragraph). 
here is the excepion  that I get in the last item of the loop (third one) 

{"message":"repeat request","label":"REPEAT_REQUEST"}

Shortly, I can create 2 sell orders but I cannot create last one and I got an exception.

In the API documentation, I did not see such a "label" definition 

I use V4 API

PS: I also added a Thread Sleep, because I thought that maybe the process is so fast however 500 ms sleep did not help me

**Comment by revilwang** [comment]
I'll report this issue back to the server implementation

**Comment by revilwang** [comment]
`REPEAT_REQUEST` is returned once specific fields are the same between two price triggered orders in 1 second per user. The fields are Market and Rule. Price and amount are NOT evaluated. You can choose to sleep for 1 second between two "identical" orders.

**Comment by ertan2002** [comment]
thank you for your reply. It worked as you said. When I put 1 second sleep, there was no error message. Thank you
